fix(btuart): check return code of kill
Killing the spawned "hciattach" process can fail. Since "set -e" isn't
set check this manually.

Fixes: f6efaa2 ("feat: Add support for Flat S")
Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/scripts/revpi-btuart b/scripts/revpi-btuart
--- a/scripts/revpi-btuart
+++ b/scripts/revpi-btuart
@@ -48,7 +48,11 @@ attach_flat_s() {
 	# At the time being the module needs a magic second initialization.
 	# Until the root-cause has been identified, this is done in order to
 	# make bluetooth usable here.
-	kill "$_hci_pid"
+	if ! kill "$_hci_pid"; then
+		printf "Error: Unable to kill process with PID %d\n" "$_hci_pid" >&2
+		return 1
+	fi
+
 	"$HCIATTACH" "$TTYDEV" any 3000000 flow
 }
 
