feat: Make init logic depend on dt compatible
In order to support different devices, make the logic depend on the
compatible string. This will allow to add further devices without
refactoring the whole code.

Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>

diff --git a/scripts/revpi-btuart b/scripts/revpi-btuart
--- a/scripts/revpi-btuart
+++ b/scripts/revpi-btuart
@@ -9,18 +9,29 @@
 HCIATTACH=/usr/bin/hciattach
 TTYDEVNAME="$1"
 
-# RevPi Flat: The BT_REG_ON signal is connected to the GPIO11 of the expander.
-BT_REG_ON_GPIO=11
-GPIOCHIP="$(basename /sys/devices/platform/soc/*.i2c/i2c-1/1-0020/gpiochip?)"
-if [ "$GPIOCHIP" != "gpiochip?" ]; then
-	# Reset the bt module in RevPi Flat
-	gpioset "$GPIOCHIP" $BT_REG_ON_GPIO=0
-	sleep 0.1
-	gpioset "$GPIOCHIP" $BT_REG_ON_GPIO=1
-	sleep 0.1
-else
-	>&2 echo "$1: ERROR: Can't find the correct gpiochip to reset the bt module."
-fi
+attach_flat() {
+	TTYDEV="$1"
+	# RevPi Flat: The BT_REG_ON signal is connected to the GPIO11 of the expander.
+	BT_REG_ON_GPIO=11
+	GPIOCHIP="$(basename /sys/devices/platform/soc/*.i2c/i2c-1/1-0020/gpiochip?)"
+	if [ "$GPIOCHIP" != "gpiochip?" ]; then
+		# Reset the bt module in RevPi Flat
+		gpioset "$GPIOCHIP" $BT_REG_ON_GPIO=0
+		sleep 0.1
+		gpioset "$GPIOCHIP" $BT_REG_ON_GPIO=1
+		sleep 0.1
+	else
+		echo >&2 "$TTYDEV: ERROR: Can't find the correct gpiochip to reset the bt module."
+	fi
 
-# Revolution Flat limits the speed to 2000000
-$HCIATTACH "$TTYDEVNAME" bcm43xx 2000000 flow
+	# Revolution Flat limits the speed to 2000000
+	"$HCIATTACH" "$TTYDEV" bcm43xx 2000000 flow
+}
+
+
+overlay="$(/bin/grep -z -m 1 'kunbus,revpi-' /proc/device-tree/compatible | tr -d '\0' | cut -f 2 -d ,)"
+case "$overlay" in
+revpi-flat)
+	attach_flat "$TTYDEVNAME"
+	;;
+esac
