fix(btuart): check return code of of hciattach
Previously the exit code of "hciattach" wasn't checked at all and no
error was returned from the "attach_flat_s" function if attaching
failed. Check the exit code manually and print and error on failure.

Fixes: f6efaa2 ("feat: Add support for Flat S")
Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>

diff --git a/scripts/revpi-btuart b/scripts/revpi-btuart
--- a/scripts/revpi-btuart
+++ b/scripts/revpi-btuart
@@ -53,7 +53,10 @@ attach_flat_s() {
 		return 1
 	fi
 
-	"$HCIATTACH" "$TTYDEV" any 3000000 flow
+	if ! "$HCIATTACH" "$TTYDEV" any 3000000 flow; then
+		printf "Error: Unable to attach %s via UART HCI\n" "$TTYDEV" >&2
+		return 1
+	fi
 }
 
 overlay="$(/bin/grep -z -m 1 'kunbus,revpi-' /proc/device-tree/compatible | tr -d '\0' | cut -f 2 -d ,)"
